source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StrikethroughLabel_Example', :exclusive => true do
  pod 'StrikethroughLabel', :path => '../'
end

target 'StrikethroughLabel_Tests', :exclusive => true do
  pod 'StrikethroughLabel', :path => '../'

  pod 'FBSnapshotTestCase'
end
